### ISSUE TITLE
Ore Spawn Question

### ISSUE THREAD

**Issue by Cheezy16** [TeamFRM/TAIGA#106]
So I went to the Nether to get some Valyrium in order to make solarium, but I cant't find it anywhere. Does it have some specific spawn areas, or is it extremely rare? I've been speed mining in the nether to try to find  any ore at all, and I haven't found one block yet.

**Comment by Zkaface** [comment]
@Cheezy16 Yes, it is very rare. But that's mainly caused by the height difference. It can spawn from level 0 to level 128!
