### ISSUE TITLE
Crash when trying to open new pages

### ISSUE THREAD

**Issue by Flabort** [TeamFRM/TAIGA#107]
http://pastebin.com/A5U4Y10v
Mantle version 1.1.4
Tinker 2.6.2
TAIGA version 1.2.5
I go to the front page of the book and click on the TAIGA block to jump to the new pages added by you guys, game logs me out and then crashes. Single player game.

I was really looking forward to looking at these pages.

**Comment by Flabort** [comment]
http://pastebin.com/SJwnU8Y6
A second crash, same version, not sure if there's any difference in the crash log.

Caused this time by going through the book page-by-page and trying to go to the right past the fletching materials.

**Comment by IdleGandalf** [comment]
Yea, @Zkaface forgot to include a texture in his commit. If he commits that texture we can push a new release.

**Comment by Zkaface** [comment]
Should be fixed now! Please download 1.2.6 and tell me if it works!

**Comment by Flabort** [comment]
It works :1st_place_medal:

**Comment by Zkaface** [comment]
@Flabort Yay. Then another one closed :-)
