### ISSUE TITLE
Magma Fluid Creation bug(?)

### ISSUE THREAD

**Issue by Cheezy16** [TeamFRM/TAIGA#114]
If you use JEI, you probably look up recipes of smeltery stuff on occasion. I do this all the time; while I was doing such things I noticed that magma fluid can only be created by magma fluid and Nitronite... which also takes magma fluid. I've already tested out lava on it too, so is there another way to get magma blocks to smelt, or do we have a self-contradictory recipe bug?

**Comment by Zkaface** [comment]
@Cheezy16 Bug, thanks, will be fixed soon!
