### ISSUE TITLE
Possible tie into Tinkers Defense

### ISSUE THREAD

**Issue by Redlotus99** [TeamFRM/TAIGA#116]
I haven't tested this yet, but it would be nice if you could tie in your items with Tinkers Defense. I have a pack I am making tonight and this may already be a thing if it is great, if not be a something possible to add.

**Comment by Flabort** [comment]
You mean [this](https://minecraft.curseforge.com/projects/tinkers-defense)?
As far as I can see, it no longer exists.

**Comment by Redlotus99** [comment]
Yes that's the one.
