### ISSUE TITLE
Analysing trait crash, part 2

### ISSUE THREAD

**Issue by chimericdream** [TeamFRM/TAIGA#117]
I suspect this is related to #89. With 1.2.6 of the mod, I'm getting the same stack trace, but a different line. This time the error is in the `getUpdateXP()` method at line 55, with the `Random.nextInt()` call.

[Here is the crash log.](https://gist.github.com/chimericdream/8046443b188b80cb21d35b356a1d3e01)

**Comment by chimericdream** [comment]
Somehow I missed that #111 was already reported as a recurrence of #89. I'm closing this as a duplicate.

**Comment by IdleGandalf** [comment]
Yea, I wished we could make a release already, but there are just too many buggy things that need attention before something like that can happen. Hopefully we come around to do that soon.
