### ISSUE TITLE
[1.2.6] Unlocalized Trait Names and No Descriptions

### ISSUE THREAD

**Issue by SPMoo66** [TeamFRM/TAIGA#119]
Crushing on Solarium parts and Leveled on Adamant parts have unlocalized names and also do not have a description

modifier.crushing.name and modifier.leveled.name appear without description on the tool parts, tools, and in the Materials And You book.

http://imgur.com/a/oY7zT

**Comment by IdleGandalf** [comment]
fixed in 1.3.1
