### ISSUE TITLE
Crash when using a cleaver

### ISSUE THREAD

**Issue by MastaC729** [TeamFRM/TAIGA#120]
Version of TAIGA: 1.10.2-1.2.6
Version of Forge: 2221

The following stacktrace occurred when I tried to kill a Creeper with my cleaver made out of Manyullyn, Vibranium, and Nihilite (it seems to be due to the Heroic trait):

http://pastebin.com/DH7ShH7r

Let me know if you need anything else to fix this issue.

**Comment by chimericdream** [comment]
I just came here to report the exact same issue. Happened twice in the span of a few minutes this evening.

**Comment by chimericdream** [comment]
Just submitted a PR for the fix. Hopefully it can get merged into the next release.
