### ISSUE TITLE
Slaughtering trait on crossbow causes a crash

### ISSUE THREAD

**Issue by Cheezy16** [TeamFRM/TAIGA#130]
I have a terrax tough rod on my crossbow, and i tried to shoot a spider with a blazerod-solarium bolt. The crossbow is also made of a paper tough binding, electrum bow limb (the crossbow was not charged at the time), and a hemp fiber bowstring. Here's the crash log:
[crash-2017-02-20_11.31.40-server.txt](https://github.com/TeamFRM/TAIGA/files/788047/crash-2017-02-20_11.31.40-server.txt)

**Comment by Cheezy16** [comment]
The same thing happened again with a creeper, for reference

**Comment by IdleGandalf** [comment]
I think this was fixed in master, closing.
