### ISSUE TITLE
[Question] ETA for 1.2.7/1.3.0?

### ISSUE THREAD

**Issue by chimericdream** [TeamFRM/TAIGA#133]
I was just curious if there is an ETA for the next release. I remember reading in a thread a little while back (can't find it now) that there's some refactoring going on, but thought I'd check in on the status.

If the answer is "when we get to it", that's cool. Thanks for all the work you put into this!

**Comment by Zkaface** [comment]
@chimericdream Right now I am totally busy with my newborn son and my new job as an civil engineer. So it gonna take some time to fix all main and minor issues! 

I apologize for the delay...

**Comment by chimericdream** [comment]
Congratulations on both! As a relatively new father myself (as well as software engineer), I can completely relate. Games and side projects are fun, but obviously not the highest priority. Take your time.
