### ISSUE TITLE
Tiberium crystals melt into dilithium

### ISSUE THREAD

**Issue by belathus** [TeamFRM/TAIGA#136]
I think [this line](https://github.com/TeamFRM/TAIGA/blob/4db215fc654f390313198e02cc1579728d2aca0c/src/main/java/com/sosnitzka/taiga/Fluids.java#L97) is responsible.

Also, tiberium crystals have no texture.

**Comment by TechieJunk** [comment]
The tiberium crystal texture is already in the master branch but hasn't been compiled officially.

As for the tiberium crystals melting into the wrong fluid.. Proposed fix here: [Link]https://github.com/TeamFRM/TAIGA/pull/145)

**Comment by IdleGandalf** [comment]
Fixed in master.
