### ISSUE TITLE
JEI not showing alloys in 1.10.2

### ISSUE THREAD

**Issue by nlades** [TeamFRM/TAIGA#153]
I've been playing singleplayer with no aid with TAIGA. I managed to get violium in my last game, but it seems i cannot progress further because i don't know the alloys. 

I searched the internet for these recipes, but the only ones (very few, to tell the truth) were outdated. The wiki tells something about four families, but i'm not capable of identifying with each family. It's a shame, cause it's a really good mod.

**Comment by IdleGandalf** [comment]
Thanks for reporting. I'll try this later this week and check if I can do anything. Maybe its a bug with JEI itself, maybe they changed something, don't know yet. 

I'm busy porting to 1.12 at the moment, so I will look at this after the port is done.

**Comment by IdleGandalf** [comment]
Ah btw, it could be helpful to get a FML log of the start of your minecraft, could you provide that on some past site (github gist, pastebin etc)

**Comment by nlades** [comment]
Well, it was NEI's problem. Just used the relase version (.19 one) and everything works fine now. Thanks for your quick answer 👍
