### ISSUE TITLE
wiki?

### ISSUE THREAD

**Issue by iluvdemomanandjunkrat** [TeamFRM/TAIGA#34]
i need a wiki please! because im now stuck at titanite! i have jei but im still confused where to go next

**Comment by tankcr** [comment]
Yes, it is difficult to figure out what alloys are required to mine the next level of alloy.

**Comment by Zkaface** [comment]
I will create a Wiki, but in respect to the upcoming 1.2 update I won't do one for 1.1.x, because it would be too many changes.

**Comment by tankcr** [comment]
Cool thanks! Quick question, how do you get from cobalt level to metiorite level to titanite level?

**Comment by Zkaface** [comment]
Don't you use NEI or a similar mod?

**Comment by tankcr** [comment]
yes I do, and it tells me mining level, but no idea what alloy to use on pick to actually achieve that level for mining.

**Comment by Zkaface** [comment]
What I can say this moment, there must be tool tips when you hover the heads of the tinker items in the nei list. I will create a small table tomorrow (in about 17 hours when I'm back from work) if you need further assistance 

Regards, Robert

**Comment by Utildayael** [comment]
Better descriptions of what the traits do would be nice. I love that you were able to add in to the Materials and You book but honestly I have no idea what most of the stuff does as the description is either a funny caption or just so vague you have no idea. I'd be happy to help with "translation" as well as I know it was said elsewhere English isn't your first language. :)

**Comment by Zkaface** [comment]
;) Ok, great!

**Comment by tankcr** [comment]
I eventually just went creative, placed all the blocks to see break level, then grabbed a ton of picks to see their pick level, and then looked at the different ores in JEI and found the recipes for smelting them. It was a bit tedious but I found the info I needed.

**Comment by Zkaface** [comment]
I now start to modify the book for informations 👍

**Comment by Zkaface** [comment]
![image](https://cloud.githubusercontent.com/assets/3511223/21786220/2a661582-d6c3-11e6-918f-8f62b3cd3b4c.png)

Finally finished the template \o/ Now I just need to write down the text.

**Comment by Zkaface** [comment]
Added en_US and de_DE files. Please watch out for the next release!
