### ISSUE TITLE
Issues with ore generation.

### ISSUE THREAD

**Issue by jacksonriggs** [TeamFRM/TAIGA#91]
Palladium, prometheum, and tiberium won't generate in my world. I've checked the config to make sure the ores were set to generate and everything is normal. Osram and abyssum still generate in the end/nether, as well as uru in the end, but I can't find anything I need to make higher teir alloys. I already had to spawn in tiberium and I don't want to have to spawn in anything else if I don't need to. I even used a digitial miner from Mekanism to search for these ores from Y0 to Y255 in a 32 block radius with no results.

**Comment by IdleGandalf** [comment]
Have you recently updated the mod? Whats your version at the moment?

**Comment by jacksonriggs** [comment]
1.2.2, the version that came out on December 24th. I updated yesterday and reset the nether world and still nothing has happened

**Comment by Zkaface** [comment]
@jacksonriggs Any relevant output in your console?

**Comment by jacksonriggs** [comment]
Nothing in the console is relating to this mod.

**Comment by Zkaface** [comment]
@jacksonriggs Then you probably have another mod which prevents my ore spawn in the nether. Difficult to say.

**Comment by jacksonriggs** [comment]
If it's that it would probably be cyclic. I can't really remove that because it would cause a lot of issues considering the amount of cyclic items I have already

**Comment by IdleGandalf** [comment]
@jacksonriggs From what version did you update?

**Comment by jacksonriggs** [comment]
I updated from 1.2 to 1.2.2. I went into the config files and disabled ore generation for Cyclic and regenerated the nether with no effect. Still no ores are spawning from TAIGA

**Comment by IdleGandalf** [comment]
Could you post the content of your TAIGA.conf? You can't find ores in the overworld & in the nether, correct?

**Comment by jacksonriggs** [comment]
ores generate fine in the overworld, they don't generate properly in the end and the nether

Here's the TAIGA.cfg:
[http://pastebin.com/0v8Z6qTt]

**Comment by zackeezy** [comment]
What's your mod list?I'm having the same problem and if it is a problem with compat then we can cross-reference out mods list.

**Comment by jacksonriggs** [comment]
Here is my modlist
http://pastebin.com/zNgNTGbG

**Comment by Cheezy16** [comment]
I've been having the exact same problem, however I dont have cyclic. I DO however have Biomes O' Plenty and Immersive Engineering, and both of those mods change oregen. Biomes O' Plenty changes the way emerald ore spawns, as well as its other gems, so that may be the primary cause.

**Comment by Cheezy16** [comment]
Chisel changes the world generation drastically through marble, limestone, and basalt. I don't know if this has anything to do with oregen though.

**Comment by jacksonriggs** [comment]
Ore in the overworld generates normally, it's the nether and the end that don't generate correctly. Could RFTools Dimensions cause this issue? Because it's catagorizing each world (Nether, end, overworld) as a dimension, which I know in vanilla doesn't happen, as each world has its own folder normally. I'll poke around more in the files and see if I can find anything else

**Comment by jacksonriggs** [comment]
I disabled all mods except for TAGIA and its dependencies, and still the only ore that generates in the nether is osram. I can't find any other ores.

**Comment by zackeezy** [comment]
Then it's not a problem with compat, it's a problem with TAIGA?

**Comment by IdleGandalf** [comment]
Huh? I'll give that a quick look in my dev environment, if it's indeed taiga then I shouldn't be able to find them as well.

**Comment by zackeezy** [comment]
I also booted it up with Just Tinkers, Mantle, and TAIGA, and the nether had none of the ores except Osram

**Comment by IdleGandalf** [comment]
There was definitely something wrong with taiga. Some parameters were mixed up, so instead of searching for netherrack the worldgen was searching for the ores to replace with netherrack (wich of course means they never even generated in the first place). Its fixed now, I'll release a new minor version in a few minutes.

**Comment by IdleGandalf** [comment]
New version 1.2.3 is now on curseforge.

**Comment by jacksonriggs** [comment]
Thank you so much :)

**Comment by IdleGandalf** [comment]
No problem, but I forgot to check the parameters for the end as well, I just noticed. Need another release  then, otherwise it kinda breaks the mod's gameplay.

**Comment by IdleGandalf** [comment]
1.2.4 on curseforge. Hopefully that's it for this issue.
