### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by CamaroKing59** [TeamFRM/TAIGA#92]
http://pastebin.com/nsEv5xV9

**Comment by IdleGandalf** [comment]
That's an odd one. Do you have a special dimension (like a void dim) that you generate new terrain in?

**Comment by IdleGandalf** [comment]
Could you try version 1.2.3 that just released? That should fix this.

**Comment by IdleGandalf** [comment]
Is there any news on this? Otherwise I'll assume it's solved and close this one.

**Comment by CamaroKing59** [comment]
The void world I have in is simple void world I believe from what I see he has it set to stop any kind of void generation in it is there anything in the config to stop ore gen in specific world's or is there a way to put something to stop it

**Comment by Zkaface** [comment]
@CamaroKing59 @IdleGandalf had some thoughts about that problem. We gonna see what we are able to do.

**Comment by Zkaface** [comment]
@CamaroKing59 Please tell me more about that world. How is it generated? Which taiga version do you use?

**Comment by CamaroKing59** [comment]
I will appreciate it I like all the alloys and stuff if gives us more stuff to work for and with for tinker's

**Comment by Zkaface** [comment]
@CamaroKing59 Please tell me which version you use and to which mod your void dimension belongs.

**Comment by CamaroKing59** [comment]
I use the latest  version and the void world is from simple void world

**Comment by CamaroKing59** [comment]
Maybe add a dimension blacklist in the config?

**Comment by CamaroKing59** [comment]
The version is 1.2.4 of taiga

**Comment by CamaroKing59** [comment]
any progress?

**Comment by Zkaface** [comment]
Please be patient, since January 1st I got a full time Job as an engineer - so it will take some more time.
@IdleGandalf said to me that there should actually be a workaround for void dimensions.

**Comment by CamaroKing59** [comment]
ok i was jw

**Comment by IdleGandalf** [comment]
Next release will contain a void dimension detection, which disables our worldgen for that dimension. For now this blacklist will not persist after server reboot, since it still needs some testing. We can make it a permanent blacklist once this has been fully tested.

**Comment by CamaroKing59** [comment]
Ty it worked
