### ISSUE TITLE
Minor Issues (Typos and grammar corrections)

### ISSUE THREAD

**Issue by Flabort** [TeamFRM/TAIGA#95]
I myself, despite only speaking English, don't have a perfect command of the language. But I have noticed some typos or incorrect usages of English, and I think by collating them all into one typo thread, and commenting to this issue thread when we find a typo, we can keep the devs from having to close unnecessary threads whenever another typo is found. 

So here's what I've found:
> src/main/resources/assets/taiga/book/en_US/ores/firstwords.json
> 
> TAIGA adds various new blocks and ores. You need to combine them in different alloys to get higher tiers,1 some better stats and special traits.
> 
> 
> The ores have to be found at special places. On the next pages, you will be teached where to find the ores and how they have to be handeled.

"...combine them **into** different alloys to get higher **tiers, with** some better..."
"...pages, you will be **taught** where..."
"...they have to be **handled.**"

I know that that particular file has a note saying it needs to be changed before next release, but unless the devs have a reason not to allow it, any more typos found can go here too. Devs (Zkaface and IdleGandalf), if there's a good reason not to have a typo thread, you can feel free to close it, and I won't be offended.

**Comment by Flabort** [comment]
LOL I should learn to look more carefully before posting an issue. Those typos I found were all fixed in the next commit.

Still, I think if any more typos are found this thread should stay here for other people.

**Comment by IdleGandalf** [comment]
Yea the book part is a big WIP. As for this "thread": I would agree if this would be a forum/board, but the way GitHub issues are meant to function (as for every other bugtracker there is as well) is that you open a issue for every specific problem there is, since tracking them in one big one would mean it is impossible to resolve such an issue, which clusters the issue tracker and it might get messy over time. That doesn't mean you need to open one issue per typo, but one per point-in-time where you found a bunch of typos would be preferable.

**Comment by IdleGandalf** [comment]
I'll leave this open until I got something setup where you can edit language files directly (some sort of translation tool) and they will be updated when our buildbot builds taiga for curseforge. I don't have an exact setup in mind yet, but that would be a solution even outside this issue tracker.

**Comment by Flabort** [comment]
Double checked before mentioning it, but with the new book pages for Jauxum and Ovium, they both have the word Karsemine in a location where their own name should be. There are a few grammatical errors in the other ores, but none so readily correctable by myself.

**Comment by Zkaface** [comment]
@Flabort That could be. It was late yesterday and I've been tired. Also please tell me where you think the errors are.

**Comment by Flabort** [comment]
Right. And my apologies, they are only typos/grammatical errors, and I didn't do great in language arts class... but here's what I see in the commit:

Capitalization in Aurorium. "but" -> "But"
Last sentence in Aurorium makes no sense. Perhaps you meant "By reworking it a few times it could gain some unique properties" for if you meant alloying it gives it new traits, or maybe you meant "This ore will be getting more properties in the future as we develop the mod".
Last sentence in Duranite could use an extra word. "...hard and you **will** need some..."
Jauxum has wrong word. "For using **Jauxum** in alloys..."
Ovium has wrong word.  "For using **Ovium** in alloys..."
Palladium has incorrect pluralization OR missing comma. "It glows**,** caused by..." or "It's glow **is** caused by..."
Another missing comma in Palladium. "...radioactivity**,** and is..."
Prometheum could use the word "the": "...heavy pressure and **the** heat it has to..."
Tiberium has words out of order. "...you **will often** discover..."
Vibranium could have the word "most" removed. "It's the rarest ore..."

**Comment by IdleGandalf** [comment]
Closing this in favour of a new issue.
