### ISSUE TITLE
Question to change Pulverizing

### ISSUE THREAD

**Issue by Cheezy16** [TeamFRM/TAIGA#99]
In Pulverizing currently, breaking a block gives you nothing at all. In some older mods of the 1.7.10 era, you were able to pulverize cobblestone/stone to gravel, then to sand, then to dust. I think that that should be applied to the trait Pulverizing so that it's worthwhile to get solarium. Ores could also be broken for the ore dusts which for the moment aren't used at all. This change would balance Solarium greatly, and keeping Super Heavy on it would still give it drawbacks to keep it from being overpowered.

**Comment by Zkaface** [comment]
Hmmm... my intention was to connect the speed of solarium with dissolving block drops for having a kind of tunneling tool. I had the problem, that if i want to clean out rooms in the depth, that my inventory was full of garbage cobblestone. Maybe I put that trait on another material and create a separate trait like you said - actually fragile is a trait which comes near for what you want.

**Comment by Cheezy16** [comment]
Ok, I see what you meant for a tunneling tool; Maybe pulverizing could go on Meteorite because the actual structure destroys the surrounding blocks?

**Comment by Zkaface** [comment]
@Cheezy16 I already had the same thought ;-)

**Comment by Zkaface** [comment]
done

**Comment by Flabort** [comment]
The name change from pulverizing to crushing has broken the lang file, in the bow materials pages it mentions Solarium has modifier.crushing.desc
